# Generated by Django 5.0.6 on 2024-07-09 16:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0003_fotografia_publicada'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='data_fotografia',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 9, 16, 59, 16, 303906, tzinfo=datetime.timezone.utc)),
        ),
    ]
