# Generated by Django 5.0.6 on 2024-07-09 17:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0004_fotografia_data_fotografia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografia',
            name='data_fotografia',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 9, 17, 21, 40, 693572, tzinfo=datetime.timezone.utc)),
        ),
    ]
